services:
  web:
    build: ./project
    env_file:
      - .env
    volumes:
      - ${DATA_FOLDER}/fastapi.db:/usr/src/app/data/fastapi.db
      #- ./project/alembic/versions:/usr/src/app/alembic/versions
      - ${DATA_FOLDER}/uploads:/usr/src/app/uploads
    environment:
      # ${...} - параметры извлекаемые из .env файла
      - SECRET_KEY=${SECRET_KEY}
      - FIRST_SUPERUSER_EMAIL=${FIRST_SUPERUSER_EMAIL}
      - FIRST_SUPERUSER_PASSWORD=${FIRST_SUPERUSER_PASSWORD}
      - DENY_CANCEL_AFTER_MINUTES_USED=${DENY_CANCEL_AFTER_MINUTES_USED}
      - AUTH_TOKEN_LIFETIME_SECONDS=${AUTH_TOKEN_LIFETIME_SECONDS}
      - BACKDATE_RESERVATION_ALLOWED_SECONDS=${BACKDATE_RESERVATION_ALLOWED_SECONDS}
      - MAX_RESERVATION_DURATION_MINUTES=${MAX_RESERVATION_DURATION_MINUTES}
      - TZ=${TZ}