services:
  nginx:
    build: ./nginx
    restart: always
    volumes:
      - ./certs:/etc/ssl/certs
    env_file:
      - .env
    networks:
      vlan:
        ipv4_address: ${MACVLAN_IP}
  web:
    hostname: web
    build: ./project
    restart: always
    env_file:
      - .env
    volumes:
      - ./data/:/usr/src/app/data/
      - ./project/alembic/versions:/usr/src/app/alembic/versions
      - ./config/:/usr/src/app/config/
networks:
  vlan:
    external: true