services:
  web:
    build: ./project
    env_file:
      - .env
    volumes:
      - ./data/:/usr/src/app/data/
      - ./project/alembic/versions:/usr/src/app/alembic/versions
      - ./config/:/usr/src/app/config/
    ports:
      - ${PUBLIC_PORT}:${PUBLIC_PORT}