services:
  web:
    build: ./project
    volumes:
      - ${DATA_FOLDER}:/usr/src/app/data/
    ports:

      - ${PUBLIC_PORT}:8000
    environment:
      # ${...} - параметры извлекаемые из .env файла
      - SECRET_KEY=${SECRET_KEY}
      - FIRST_SUPERUSER_EMAIL=${FIRST_SUPERUSER_EMAIL}
      - FIRST_SUPERUSER_PASSWORD=${FIRST_SUPERUSER_PASSWORD}
      - DENY_CANCEL_AFTER_MINUTES_USED=${DENY_CANCEL_AFTER_MINUTES_USED}
      - TZ=${TZ}