services:
  nginx:
    build: ./nginx
    restart: always
    volumes:
      - ./certs:/etc/ssl/certs
    env_file:
      - .env
    networks:
      vlan:
        ipv4_address: ${MACVLAN_IP}
      internalbr:
        ipv4_address: 10.${SUBNET}.0.2

  web:
    hostname: web
    build: ./project
    restart: always
    env_file:
      - .env
    volumes:
      - ./data/:/usr/src/app/data/
      - ./project/alembic/versions:/usr/src/app/alembic/versions
      - ./config/:/usr/src/app/config/
    networks:
      internalbr:
        ipv4_address: 10.${SUBNET}.0.3

networks:
  vlan:
    external: true
  internalbr:
    driver: bridge
    ipam:
      config:
        - subnet: 10.${SUBNET}.0.0/24