"""Added Timesheet settings table

Revision ID: 5a76a3780208
Revises: bde440022ed5
Create Date: 2025-07-16 23:22:42.057463

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a76a3780208'
down_revision = 'bde440022ed5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('timesheet_settings',
    sa.Column('spreadsheet_url', sa.Text(), nullable=False),
    sa.Column('worksheet', sa.Text(), nullable=False),
    sa.Column('with_service_account', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('spreadsheet_url', 'worksheet', name='spreadsheet_worksheet_uc')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timesheet_settings')
    # ### end Alembic commands ###
