"""empty message

Revision ID: 8bfc0c3c7742
Revises: 98950bb5aa04
Create Date: 2025-06-30 00:48:10.760743

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bfc0c3c7742'
down_revision = '98950bb5aa04'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('adGroupDN', sa.Text(length=500), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('adGroupDN'),
    sa.UniqueConstraint('name')
    )
    op.create_table('grouproompermission',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('max_future_reservation', sa.Interval(), nullable=True),
    sa.Column('meetingroom_id', sa.Integer(), nullable=True),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id'], ),
    sa.ForeignKeyConstraint(['meetingroom_id'], ['meetingroom.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('group_id', 'meetingroom_id', name='_group_to_room_uc')
    )
    with op.batch_alter_table('meetingroom', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon', sa.String(length=100), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('group_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key("user_group_id_constr", 'group', ['group_id'], ['id'])
        batch_op.drop_column('birthdate')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('birthdate', sa.DATETIME(), nullable=True))
        batch_op.drop_constraint("user_group_id_constr", type_='foreignkey')
        batch_op.drop_column('group_id')

    with op.batch_alter_table('meetingroom', schema=None) as batch_op:
        batch_op.drop_column('icon')

    op.drop_table('grouproompermission')
    op.drop_table('group')
    # ### end Alembic commands ###
