"""empty message

Revision ID: 98950bb5aa04
Revises: 4d76343b4dc4
Create Date: 2025-04-02 01:35:34.069238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98950bb5aa04'
down_revision = '4d76343b4dc4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditevent',
    sa.Column('time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('description', sa.Text(length=1000), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('auditevent')
    # ### end Alembic commands ###
