"""Added confirmed_activityflag to reservation

Revision ID: a14254a2bb7c
Revises: 5a76a3780208
Create Date: 2025-07-17 23:46:29.914674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a14254a2bb7c'
down_revision = '5a76a3780208'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('confirmed_activity', sa.Boolean(), nullable=False, server_default="0"))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.drop_column('confirmed_activity')
    # ### end Alembic commands ###
