"""added activity log

Revision ID: bde440022ed5
Revises: 8bfc0c3c7742
Create Date: 2025-07-16 19:46:18.992116

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bde440022ed5'
down_revision = '8bfc0c3c7742'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activity_log',
    sa.Column('received_at_time', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('computer_time', sa.DateTime(), nullable=False),
    sa.Column('meetingroom_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meetingroom_id'], ['meetingroom.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auditevent', schema=None) as batch_op:
        batch_op.alter_column('time',
               existing_type=sa.DATETIME(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('description',
               existing_type=sa.TEXT(length=1000),
               nullable=False)

    with op.batch_alter_table('grouproompermission', schema=None) as batch_op:
        batch_op.alter_column('max_future_reservation',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('meetingroom_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('group_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.alter_column('from_reserve',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('to_reserve',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('meetingroom_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reservation', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('meetingroom_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('to_reserve',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('from_reserve',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('grouproompermission', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'group', ['group_id'], ['id'])
        batch_op.alter_column('group_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('meetingroom_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('max_future_reservation',
               existing_type=sa.DATETIME(),
               nullable=True)

    with op.batch_alter_table('auditevent', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(length=1000),
               nullable=True)
        batch_op.alter_column('time',
               existing_type=sa.DATETIME(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    op.drop_table('activity_log')
    # ### end Alembic commands ###
